image: node:latest

setup-job:
  stage: setup
  script:
    - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc

install-job:
  stage: build
  dependencies:
    - setup-job
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test-job:
  stage: test
  dependencies:
    - install-job
  script:
    - echo "This job tests something, but takes more time than test-job1."

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys from the branch."
    - CI=false npm run build
    - echo "-- build completed succesfully"
  dependencies:
    - install-job
    - test-job
  only:
    - main
