image: node:latest

install-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm install
  artifacts:
    paths:
      - node_modules/

test-job:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - CI=false npm run build
    - echo "-- build completed succesfully"
  dependencies:
    - install-job
  only:
    - main
